Add 3 Sites
wdhdev/free-for-life pull request #56
Opened 2024-04-26 16:04 UTC by Helixoo

Add huggingface, onlinegdb and blackbox ai

2024-04-26 23:38 UTC, wdhdev requested changes
Please place them in alphabetical order.

2024-04-27 06:45 UTC, Helixoo commented
I changed

2024-04-27 11:02 UTC, wdhdev commented on data/Artificial_Intelligence.md
> +| [Hugging Face](https://huggingface.co) | Hugging Face is a platform that allows you to discover, create and develop language models in artificial intelligence. |
```suggestion
| [Hugging Face](https://huggingface.co) | The platform where the machine learning community collaborates on models, datasets, and applications. |
```

2024-04-27 11:02 UTC, wdhdev commented on data/Code_Editors.md
> +| [OnlineGDB](https://www.onlinegdb.com) | Online compiler and Debugger for c/c++ and other languages. |
```suggestion
| [OnlineGDB](https://www.onlinegdb.com) | Online compiler and debugger for C/C++ and other languages. |
```

2024-04-27 11:02 UTC, wdhdev commented on data/Code_Generation.md
> +| [Blackbox](https://www.blackbox.ai) | Blackbox is an ai that is successful in generating code. |
```suggestion
| [Blackbox](https://www.blackbox.ai) | AI code generation, chat and search. |
```

2024-04-27 11:02 UTC, wdhdev approved these changes

2024-04-27 11:02 UTC, merged